### ISSUE TITLE
Node-RED isn't working, ioBroker installed in Docker Environment

### ISSUE THREAD

**Issue by nicedevil007** [ioBroker/ioBroker.node-red#85]
Hey guys,

I tryed it so much now, but I can't get it to work :(
I have a working installation of my docker with swarm activated.

I tryed running ioBroker just with the docker run command and also with my swarm compose file. Everytime I get ioBroker running but not the adapter of node-red.

The logfile tells me:

```
node-red.0 | 2020-02-23 20:45:24.091 | info | (1081) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- | -- | -- | --
node-red.0 | 2020-02-23 20:45:21.683 | warn | (1103) 23 Feb 20:45:21 - [warn] Kein aktives Projekt: Standarddatei für DatenFlows verwenden
node-red.0 | 2020-02-23 20:45:20.729 | warn | (1103) 23 Feb 20:45:20 - [warn] server.httpadminauth-deprecated
node-red.0 | 2020-02-23 20:45:20.464 | info | (1103)  Starting node-red: --max-old-space-size=128  /opt/iobroker/node_modules/node-red/red.js -v --settings  /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-02-23 20:45:20.400 | info | (1103) starting. Version 1.13.0 in /opt/iobroker/node_modules/iobroker.node-red, node: v10.19.0
node-red.0 | 2020-02-23 20:45:20.091 | warn | (1081) Got terminate signal. Checking desired PID: 1103 vs own PID 1081
node-red.0 | 2020-02-23 20:45:20.090 | warn | (1081) Got terminate signal. Checking desired PID: 0 vs own PID 1081
```

The docker-compose I'm using for my stack deployment looks like this:
```
version: '3.7'

volumes:
  iobroker_data:

networks:
  default:

services:
  iobroker:
    image: buanet/iobroker:latest
    networks:
      default:
    ports:
      - 9981:8081
    volumes:
      - iobroker_data:/opt/iobroker
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - ADMINPORT=8081
      - LANG=de_DE.UTF-8
      - LANGUAGE=de_DE:de
      - LC_ALL=de_DE.UTF-8
      - PACKAGES=vi nano
```

I was also trying to let ioBroker run on network setting slike this in my stackfile:

```
networks:
  default:
    external:
      host:
```

But this won't work at all. I can't even access ioBroker.
